questions = [
    "What are the actions taken against sexual harassment Act?",
    "What is the role of chairperson in the CMGI?" ,
    "What is the role of the CMGI?",
    "what led to any person for suspension as punishment?",
]


ground_truth_answers = [
    "CMGI is not only confined to dealing with complaints of Sexual Harassment towards women but also towards members of other genders and to work for creating awareness, sensitization, counselling, and educating about gender issues. The CMGI Policy will be followed in conjunction with the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 (14 of 2013) and other relevant guidelines." ,
    "A Chairperson who shall be a tenured woman faculty member at the IIMA, nominated by the Director;  Provided that in case a tenured woman faculty is not available, the Chairperson shall be nominated from other offices or administrative units of the workplace referred to in sub-section 2(k)The Chairperson shall be responsible for the overall functioning of the CMGI and shall be the final authority in all matters related to the CMGI. The Chairperson shall be responsible for the implementation of the CMGI Policy and shall ensure that the CMGI Policy is followed in conjunction with the Sexual Harassment",
    "The Committee for Managing Gender Issues (CMGI) is responsible for addressing complaints related to sexual harassment at the Indian Institute of Management Ahmedabad (IIMA). Its key roles include: 1. **Creating Awareness**: CMGI works to create awareness about what constitutes sexual harassment and conducts sensitization programs for faculty, managers, and students. 2. **Handling Complaints**: The committee is a formal body where complaints of sexual harassment can be filed. It evaluates complaints, ensures a fair inquiry process, and provides assistance to complainants. 3. **Confidentiality**: CMGI is tasked with maintaining the confidentiality of all complaints and the identities of individuals involved, including complainants, respondents, and witnesses. 4. **Interim Measures**: The committee can recommend immediate protective measures for complainants while their cases are being investigated, such as transferring the complainant or respondent to a different department. 5. **Recommendations for Action**: After conducting inquiries, CMGI provides recommendations regarding disciplinary actions against those found guilty of sexual harassment. This could include penalties such as a written apology, suspension, or even termination. 6. **Education and Training**: CMGI organizes workshops and training sessions to educate staff and students about gender issues and to promote a safe and inclusive campus environment.7. **Protection Against Retaliation**: The committee ensures that individuals who report harassment are protected from any form of retaliation or victimization." ,
    "place an employee under suspension: 1. where a disciplinary proceeding against him is contemplated or is pending or 2. where in the opinion of the authority aforesaid, he has engaged himself in activities prejudicial to the interest of the security of the State; or 3. where a case against him in respect of any criminal offence is under investigation, inquiry or trial: Provided that, where the order of suspension is made by an authority lower than the appointing  authority,  such  authority  shall  forthwith  Report  to  the  appointing  authority  the  circumstances in which the order was made. 4. An employee shall be deemed to have been placed under suspension by order of appointing authority: a)  With effect from the date of his detention, if he is detained in custody, whether on a criminal charge or otherwise, for a period exceeding forty-eight hours. " ,
]


predicted_answers = [
    "The Institute has established the Committee for Managing Gender Issues (CMGI) to address sexual harassment in accordance with the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013. Here are the key actions related to the Act:\n\n1. **Establishment of Internal Committee (IC)**: CMGI serves as the internal complaints committee, empowered to handle complaints of sexual harassment, including against men and other genders.\n\n2. **Process for Complaints**:\n   - Complaints must be submitted in writing to CMGI within three months of the incident.\n   - Assistance is provided to individuals who may require help in documenting their complaints.\n\n3. **Confidentiality**: The identity of those involved in the complaint process is kept confidential to protect complainants and witnesses from retaliation or victimization.\n\n4. **Inquiry Procedure**:\n   - Upon receipt of a complaint, the CMGI will initiate an inquiry, which must be completed within a specified time frame (typically within 90 days).\n   - Respondents are given the opportunity to respond to the allegations made against them.\n\n5. **Interim Measures**: The committee can recommend interim measures to protect the complainant during the inquiry process, such as temporary transfers or leave.\n\n6. **Punishment for Offenders**:\n   - If found guilty, offenders may face various penalties, including counseling, warnings, suspension, transfer, or termination from the Institute.\n   - The committee has specific guidelines for determining the nature of the punishment based on the severity of the harassment.\n\n7. **Protection Against Reprisals**: The Institute prohibits retaliation against anyone who has filed a complaint or participated in an inquiry. Violations can lead to additional disciplinary actions.\n\n8. **Awareness and Training**: Initiatives are taken to educate staff and students on gender issues, rights, and responsibilities related to preventing sexual harassment.\n\n9. **Policy Amendments**: The Institute reserves the right to amend the sexual harassment policy to stay compliant with any changes in legislation.\n\n10. **Reporting**: Regular reporting of grievances and action taken is submitted to the Executive Authority, ensuring accountability in dealing with harassment cases.\n\nThese actions form a comprehensive approach to preventing and addressing sexual harassment within the Institute, aligning with national legislation and promoting a safe workplace environment.", 
    "The role of the Chairperson in the Committee for Managing Gender Issues (CMGI) at the Indian Institute of Management Ahmedabad (IIMA) includes the following responsibilities:\n\n1. **Leadership**: The Chairperson is a tenured woman faculty member at IIMA, nominated by the Director. She leads the CMGI in handling matters related to gender issues, including complaints of sexual harassment.\n\n2. **Committee Composition**: The Chairperson is responsible for overseeing the composition of the committee, which includes two faculty members, two non-teaching employees, and three students, ensuring diversity and representation.\n\n3. **Conduct of Proceedings**: The Chairperson manages the proceedings when a complaint of sexual harassment is brought forward. This involves forming a sub-committee for inquiries and ensuring procedures are followed appropriately.\n\n4. **Recommendations**: After reviewing complaints and evidence, the Chairperson facilitates the committee's recommendations to the Director for appropriate actions based on findings.\n\n5. **Confidentiality**: The Chairperson ensures that confidentiality is maintained throughout the process of inquiry and handling of complaints, protecting the identities of the complainants and witnesses.\n\nOverall, the Chairperson plays a crucial role in ensuring the effective functioning of the CMGI, promoting a safe and respectful environment at IIMA, and implementing the provisions of gender-related policies.",
    "The Committee for Managing Gender Issues (CMGI) is responsible for addressing complaints related to sexual harassment at the Indian Institute of Management Ahmedabad (IIMA). Its key roles include:\n\n1. **Creating Awareness**: CMGI works to create awareness about what constitutes sexual harassment and conducts sensitization programs for faculty, managers, and students.\n\n2. **Handling Complaints**: The committee is a formal body where complaints of sexual harassment can be filed. It evaluates complaints, ensures a fair inquiry process, and provides assistance to complainants.\n\n3. **Confidentiality**: CMGI is tasked with maintaining the confidentiality of all complaints and the identities of individuals involved, including complainants, respondents, and witnesses.\n\n4. **Interim Measures**: The committee can recommend immediate protective measures for complainants while their cases are being investigated, such as transferring the complainant or respondent to a different department.\n\n5. **Recommendations for Action**: After conducting inquiries, CMGI provides recommendations regarding disciplinary actions against those found guilty of sexual harassment. This could include penalties such as a written apology, suspension, or even termination.\n\n6. **Education and Training**: CMGI organizes workshops and training sessions to educate staff and students about gender issues and to promote a safe and inclusive campus environment.\n\n7. **Protection Against Retaliation**: The committee ensures that individuals who report harassment are protected from any form of retaliation or victimization.\n\nOverall, the CMGI aims to foster a safe working environment at IIMA by addressing, preventing, and reducing incidents of sexual harassment within the institution.", 
    "A person may be suspended as punishment for the following reasons:\n\n1. **Engaging in Activities Prejudicial to the Interest of the Institution**: If an employee is found to be involved in activities that harm the interests or reputation of the Institute, they may be placed under suspension.\n\n2. **Legal Issues**: An employee who is arrested on a criminal charge or detained under legal processes may be considered for suspension. If the competent authority believes that the employee's conduct during such detention is detrimental to the institution's interests, suspension can be enforced.\n\n3. **Serious Misconduct**: Committing acts that amount to serious misconduct, such as theft, dishonesty, or breaching discipline will lead to suspension.\n\n4. **Insubordination**: Willful insubordination or disobedience of lawful orders given by superiors can result in suspension.\n\n5. **Neglect of Duty**: Habitual negligence or neglect of work responsibilities without sufficient cause can also be grounds for suspension.\n\n6. **Violation of Policies**: Repeated breaches of conduct rules, including engaging in acts of sexual harassment or substance abuse, will lead to disciplinary action and potential suspension.\n\nIn all cases, the suspension is often a precursor to a more formal disciplinary process, which may include an inquiry into the employee's conduct."
]